name: Robo Vagas Inatel (Canal)

on:
  schedule:
    # Roda √†s 09h, 13h, 17h e 21h (Hor√°rio de Bras√≠lia)
    # A sintaxe √©: minuto horas * * *
    - cron: '0 12,16,20,0 * * *'

  workflow_dispatch: # Mant√©m o bot√£o manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ESSENCIAL: Permite salvar o CSV atualizado
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Instalando bibliotecas
        run: pip install requests beautifulsoup4

      - name: Rodando o script
        env:
          # Conectando suas chaves secretas ao c√≥digo Python
          TELEGRAM_TOKEN: ${{ secrets.TOKEN_BOT }}
          CANAL_ID: ${{ secrets.CANAL_ID }}
        run: python scraper.py

      - name: Guardando o hist√≥rico (Salvar CSV)
        run: |
          git config --global user.name "Bot Vagas"
          git config --global user.email "bot@inatel.br"
          # Adiciona o CSV gerado
          git add vagas_estagio_inatel.csv
          # S√≥ faz commit se houve mudan√ßa (novas vagas)
          git diff --quiet && git diff --staged --quiet || (git commit -m "ü§ñ Atualiza√ß√£o autom√°tica de vagas" && git push)
