name: Robo Vagas Inatel

on:
  schedule:
    - cron: '0 11-23 * * *' # Roda de hora em hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiss√£o OBRIGAT√ìRIA para salvar o CSV
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Instalando bibliotecas
        run: pip install requests beautifulsoup4

      - name: Rodando o script
        env:
          # AQUI EST√Å O PULO DO GATO:
          # O Python pede "TELEGRAM_TOKEN", e a gente entrega o seu "TOKEN_BOT"
          TELEGRAM_TOKEN: ${{ secrets.TOKEN_BOT }}
          
          # O Python pede "CANAL_ID", e a gente entrega o segredo que voc√™ acabou de criar
          CANAL_ID: ${{ secrets.CANAL_ID }}
        run: python scraper.py

      - name: Guardando o hist√≥rico (Salvar CSV no GitHub)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          # Adiciona o CSV gerado
          git add vagas_estagio_inatel.csv
          # S√≥ faz commit se houve mudan√ßa nas vagas
          git diff --quiet && git diff --staged --quiet || (git commit -m "ü§ñ Bot: Lista de vagas atualizada" && git push)
